name: CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This job will build the project"

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: echo "This job will run the tests"
      
  show-date:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Display current date
        run: date
